language: python
python:
- 2.7
sudo: false
services:
- redis
install:
- python bootstrap.py -c ${BUILDOUT}
- bin/buildout -N -t 3 -c ${BUILDOUT}
script:
- bin/test
- bin/code-analysis
env:
  matrix:
  - BUILDOUT=travis.cfg
  - BUILDOUT=travis-redis.cfg
cache:
  directories:
  - eggs
